#!/bin/sh

case "$1" in
    start)
        echo "loading scull module"
        scull_load
        ;;
    stop)
        echo "unloading scull module"
        scull_unload
        ;;
    *)
        echo "Usage $0 {start|stop}"
        exit 1
esac
